engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
	csslint:
			enabled: true
	duplication:
		enabled: true
		config:
			languages:
			- javascript
ratings:
  paths:
    - src/**
    - **.js
exclude_paths:
  - karma/**
  - vendor/**
  - src/**/*.spec.js
  - build/**
  - Gruntfile.js
  - karma.conf.js
  - .eslintrc.js
  - .editorconfig
  - .codeclimate.yml
  - LICENSE
  - README.md
  - bower.json
  - package.json
  - .*.json
  - .*.yml
  - .*rc
