FROM terranodo/exchange:registry

# Copy css to the right folder, assumes MapLoom is the same version
COPY ../../bin/assets/MapLoom-1.5.4.css /usr/local/lib/python2.7/site-packages/maploom/static/maploom/assets/
# Copy js to the right folder, assumes MapLoom is the same version
COPY ../../bin/assets/MapLoom-1.5.4.css /usr/local/lib/python2.7/site-packages/maploom/static/maploom/assets/
